### ISSUE TITLE
Add Blueprints for Various Parts

### ISSUE THREAD

**Issue by akrigline** [RobotsAndPencils/react-gantry#13]
Using some blueprinting/templating engine, automate the creation of the following within a react-gantry project:
* duck
* container
* component
* view

**Comment by akrigline** [comment]
Personally I recommend and will attempt this with [Hygen](http://www.hygen.io/). But other libraries ([redux-cli](https://github.com/SpencerCDixon/redux-cli), and [plop](https://plopjs.com) are the two I am aware of) could work.

**Comment by stuarttannehill-rp** [comment]
I believe this is sorted with the latest PR merge but I am not sure what to do with this issue? Do they get "closed" or have some other status set?
