### ISSUE TITLE
Get Routing Working

### ISSUE THREAD

**Issue by stuarttannehill-rp** [RobotsAndPencils/react-gantry#14]
Need to set the project up to support react-router while working correctly with redux.

**Comment by akrigline** [comment]
A couple things we need to think about here are:
What Router do we want to use? Normally people just use the [BrowserRouter](https://reacttraining.com/react-router/web/api/BrowserRouter). But there's a good number of pros to using a connected-router as discussed [here](https://reacttraining.com/react-router/web/guides/redux-integration).

Pros include:
- Theoretically being able to "Timetravel debug" if your route (and everything else) is in state, you just need the state in which a bug happens to be able to see how that bug happened more easily. I've personally never been able to actually accomplish this, as often some compromise is made in the interest of time.
- Routing via dispatch can be useful and convenient.

Cons:
- Uncertain how well supported this option is.
