### ISSUE TITLE
Document SVG useage

### ISSUE THREAD

**Issue by stuarttannehill-rp** [RobotsAndPencils/react-gantry#26]
Briefly document SVG usage (inline and as an img src) in the ReadMe. Maybe throw in a little about what we are doing in Webpack to handle them.

**Comment by akrigline** [comment]
This is already documented in the TECH.md file here: [Example SVG Imports](https://github.com/RobotsAndPencils/react-gantry/blob/master/TECH.md#example-svg-imports).
